# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlantBook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlantBook
  pod “BaiduMapKit” #百度地图SDK
  pod 'BmobSDK' #Bmob数据库SDK
  pod 'Kingfisher', '~> 4.0' #引入Kingfisher做图片管理库
end
